name:                elm-haskell-state-diagram
version:             0.1.0.0
github:              "githubuser/elm-haskell-state-diagram"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2018 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/elm-haskell-state-diagram#readme>

dependencies:
- base >= 4.7 && < 5
- text
- containers
- time
- filepath
- directory
- process
- ansi-terminal


library:
  source-dirs: src
  ghc-options:
    -Wincomplete-patterns

executables:
  elm-haskell-state-diagram-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wincomplete-patterns
    dependencies:
    - elm-haskell-state-diagram

tests:
  elm-haskell-state-diagram-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - elm-haskell-state-diagram
